USE UNIVER;

CREATE TRIGGER Task8_Trigger ON TEACHER INSTEAD OF DELETE AS RAISERROR(N'Удаление запрещено', 10, 1);
    RETURN;

DELETE FROM TEACHER WHERE TEACHER = 'SMLV';
SELECT * FROM TR_AUDIT;
-- DROP TRIGGER Task8_Trigger, Task7_Trigger, TR_TEACHER_DEL1, TR_TEACHER_DEL2, TR_TEACHER_DEL3, TR_TEACHER_INS, TR_TEACHER_DEL, TR_TEACHER_UPD, TR_TEACHER;