USE UNIVER;

-- DROP TRIGGER TR_TEACHER;

CREATE TRIGGER TR_TEACHER_DEL1 ON TEACHER AFTER DELETE
    AS PRINT N'Первый триггер';
    RETURN;

CREATE TRIGGER TR_TEACHER_DEL2 ON TEACHER AFTER DELETE
    AS PRINT N'Второй триггер';
    RETURN;

CREATE TRIGGER TR_TEACHER_DEL3 ON TEACHER AFTER DELETE
    AS PRINT N'Третий триггер';
    RETURN;

EXECUTE sp_settriggerorder 'TR_TEACHER_DEL3', 'First', 'DELETE';
EXECUTE sp_settriggerorder 'TR_TEACHER_DEL2', 'Last', 'DELETE';

INSERT INTO TEACHER (TEACHER, TEACHER_NAME, GENDER, PULPIT) VALUES ('KAS', N'Климович Антон Сергеевич', 'M', 'ISiT');
DELETE FROM TEACHER WHERE TEACHER = 'KAS';