USE UNIVER;

SELECT CASE
    WHEN NOTE BETWEEN 0 AND 3 THEN N'Пересдача'
    WHEN NOTE BETWEEN 4 AND 6 THEN N'Неплохо'
    WHEN NOTE BETWEEN 7 AND 9 THEN N'Вообще супер'
    ELSE N'Ты вообще кто?'
END,
       NAME, NOTE
FROM PROGRESS INNER JOIN STUDENT S on S.IDSTUDENT = PROGRESS.IDSTUDENT
