USE UNIVER;

BEGIN TRY
    INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME)
    VALUES ('203-1', 'LK-K', '1214', '203-1');
end try
begin catch
    PRINT ERROR_NUMBER();
    PRINT ERROR_MESSAGE();
    PRINT ERROR_LINE();
    PRINT ERROR_PROCEDURE();
    PRINT ERROR_SEVERITY();
    PRINT ERROR_STATE();
end catch