USE UNIVER
--1. Всё с левой таблицы
SELECT PULPIT.FACULTY, PULPIT.PULPIT, PULPIT.PULPIT_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
		ON PULPIT.PULPIT = TEACHER.PULPIT
			WHERE TEACHER.TEACHER IS NULL
--2.Всё с правой таблицы
SELECT TEACHER.GENDER, TEACHER.PULPIT, TEACHER.TEACHER_NAME
	FROM PULPIT FULL OUTER JOIN TEACHER
		ON PULPIT.PULPIT = TEACHER.PULPIT
			WHERE TEACHER.TEACHER IS NOT NULL
--3. С обеих таблиц
SELECT * FROM PULPIT FULL OUTER JOIN TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT