use UNIVER;
--INSERT INTO FACULTY (FACULTY, FACULTY_NAME)
--	VALUES ('NF', 'New faculty');
SELECT DISTINCT FACULTY_NAME FROM FACULTY
 WHERE NOT EXISTS (SELECT * FROM PULPIT WHERE PULPIT.FACULTY = FACULTY.FACULTY)