use UNIVER;
SELECT DISTINCT PULPIT.PULPIT_NAME
	FROM FACULTY, PULPIT, PROFESSION
		WHERE FACULTY.FACULTY = PULPIT.FACULTY
		AND FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION WHERE PROFESSION.PROFESSION_NAME LIKE '%tekhnologiya%' OR PROFESSION.PROFESSION_NAME LIKE '%tekhnologii%');