use UNIVER;
SELECT TOP 1 (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT LIKE 'OAiP')[OAiP],
				 (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT LIKE 'BD')[BD],
				 (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT LIKE 'SUBD')[SUBD]
FROM SUBJECT;