USE UNIVER;
GO
ALTER PROCEDURE PSUBJECT @p varchar(20)
AS
    BEGIN
        DECLARE @k int = (SELECT COUNT(*) FROM SUBJECT);
        SELECT * FROM SUBJECT WHERE PULPIT = @p;
    END;

CREATE TABLE #SUBJECT
(
    SUBJECT char(10),
    SUBJECT_NAME varchar(100),
    PULPIT char(20)
)

INSERT #SUBJECT EXEC PSUBJECT @p = 'ISiT';
INSERT #SUBJECT EXEC PSUBJECT @p = 'TL';
SELECT * FROM #SUBJECT;