use UNIVER;

SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPE, 
	   MAX(AUDITORIUM_CAPACITY) [Максимальная_вместимость],
	   MIN(AUDITORIUM_CAPACITY) [Минимальная_вместимость],
	   AVG(AUDITORIUM_CAPACITY) [Средняя_вместимость],
	   SUM(AUDITORIUM_CAPACITY) [Суммарная_вместимость],
	   COUNT(*) [Количество_аудиторий]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPE