USE UNIVER;
SELECT
  FACULTY.FACULTY_NAME,
  GROUPS.PROFESSION,
  (2014 - GROUPS.YEAR_FIRST) [Курс],
  ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS Средняя_отметка_за_экзамены
FROM
  FACULTY
  JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
  JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY
  FACULTY.FACULTY_NAME,
  GROUPS.PROFESSION,
  GROUPS.YEAR_FIRST
ORDER BY
  Средняя_отметка_за_экзамены DESC;
