USE UNIVER;

SELECT FACULTY, PROFESSION, SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))), 2) [Средняя_отметка]
FROM GROUPS INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY = 'TOV'
GROUP BY PROFESSION, SUBJECT, FACULTY
EXCEPT
SELECT FACULTY, PROFESSION, SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))), 2) [Средняя_отметка]
FROM GROUPS INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY = 'HTiT'
GROUP BY PROFESSION, SUBJECT, FACULTY