USE UNIVER;

SELECT FACULTY.FACULTY, PROFESSION, SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))), 2) [Средняя_отметка]
FROM FACULTY
  JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
  JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY = 'TOV'
GROUP BY CUBE (PROFESSION, SUBJECT, FACULTY.FACULTY)
EXCEPT
SELECT FACULTY.FACULTY, PROFESSION, SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))), 2) [Средняя_отметка]
FROM FACULTY
  JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
  JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY = 'TOV'
GROUP BY ROLLUP (SUBJECT, FACULTY.FACULTY, PROFESSION)